# Generated by Django 3.1.7 on 2021-06-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commenting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcomment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
    ]
