# Generated by Django 2.2 on 2021-08-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210806_1813'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owned_ebooks',
            field=models.ManyToManyField(to='catalog.Book', verbose_name='کتاب های الکترونیکی'),
        ),
    ]
