# Generated by Django 3.1.7 on 2021-06-17 23:09

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['bottom', 'right'], force_format=None, keep_meta=True, null=True, quality=100, size=[225, 225], upload_to='books_images/', verbose_name='تصویر')),
                ('file', models.FileField(blank=True, null=True, upload_to='books_files/', verbose_name='فایل')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('date_of_publish', models.DateField(verbose_name='سال چاپ')),
                ('type', models.CharField(choices=[('p', 'نسخه چاپی'), ('a', 'نسخه صوتی')], default='p', max_length=1, verbose_name='نوع چاپ')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='مجوز دریافت نظرات')),
                ('authors', models.ManyToManyField(to='catalog.Author', verbose_name='نویسندگان')),
                ('categories', models.ManyToManyField(to='catalog.Category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
    ]
