# Generated by Django 2.2 on 2021-08-06 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210806_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('date_of_publish', 'title'), 'verbose_name': 'کتاب', 'verbose_name_plural': 'کتاب ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category',), 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.AlterField(
            model_name='book',
            name='summery_file',
            field=models.FileField(blank=True, null=True, upload_to='books_summery_files/', verbose_name='فایل خلاصه'),
        ),
        migrations.CreateModel(
            name='PrintedBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Book')),
                ('authors', models.ManyToManyField(to='catalog.Author', verbose_name='نویسندگان')),
                ('categories', models.ManyToManyField(to='catalog.Category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'کتاب چاپی',
                'verbose_name_plural': 'کتاب های چاپی',
                'ordering': ('date_of_publish', 'title'),
            },
            bases=('catalog.book', models.Model),
        ),
        migrations.CreateModel(
            name='ElectronicBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.Book')),
                ('book_file', models.FileField(blank=True, null=True, upload_to='books_files/', verbose_name='فایل')),
                ('authors', models.ManyToManyField(to='catalog.Author', verbose_name='نویسندگان')),
                ('categories', models.ManyToManyField(to='catalog.Category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'کتاب الکترونیکی',
                'verbose_name_plural': 'کتاب های الکترونیکی',
                'ordering': ('date_of_publish', 'title'),
            },
            bases=('catalog.book', models.Model),
        ),
    ]
