# Generated by Django 3.1.7 on 2021-05-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210501_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
