# Generated by Django 3.1.7 on 2021-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210507_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_posted',
        ),
        migrations.AddField(
            model_name='order',
            name='post_code',
            field=models.IntegerField(blank=True, default=0, verbose_name='کد رهگیری پستی'),
        ),
    ]
