# Generated by Django 3.1.7 on 2021-05-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210511_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='کد رهگیری پستی'),
        ),
    ]
