# Generated by Django 3.1.7 on 2021-06-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20210512_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد رهگیری پستی'),
        ),
    ]
