# Generated by Django 3.1.7 on 2021-06-17 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد های خرید',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد')),
            ],
            options={
                'verbose_name': 'قلم سبد خرید',
                'verbose_name_plural': 'اقلام سبد خرید',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('post_code', models.IntegerField(blank=True, null=True, verbose_name='کد رهگیری پستی')),
                ('address', models.TextField(verbose_name='آدرس ارسال')),
                ('postal_code', models.CharField(default=0, max_length=10, verbose_name='کد پستی')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100, verbose_name='عنوان قلم سفارش')),
                ('item_price', models.IntegerField(verbose_name='قیمت')),
                ('item_quantity', models.IntegerField(verbose_name='تعداد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش',
            },
        ),
    ]
