# Generated by Django 3.1.7 on 2021-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210618_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد رهگیری پستی'),
        ),
    ]
