# Generated by Django 3.1.7 on 2021-04-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='data_of_publish',
            new_name='date_of_publish',
        ),
    ]
