# Generated by Django 3.1.7 on 2021-04-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210417_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
