# Generated by Django 3.1.7 on 2021-04-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0004_add_object_pk_is_removed_index'),
        ('catalog', '0004_bookcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookComment',
        ),
    ]
