# Generated by Django 3.1.7 on 2021-04-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20210424_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_of_publish',
            field=models.DateField(),
        ),
    ]
