# Generated by Django 3.1.7 on 2021-04-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20210428_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('p', 'نسخه چاپی'), ('a', 'نسخه صوتی')], default='p', max_length=1),
        ),
    ]
