# Generated by Django 3.1.7 on 2021-05-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20210507_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='category'),
        ),
    ]
