# Generated by Django 3.1.7 on 2021-05-07 18:14

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20210507_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'نویسنده', 'verbose_name_plural': 'نویسندگان'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'کتاب', 'verbose_name_plural': 'کتاب ها'},
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='book',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='مجوز دریافت نظرات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='catalog.Author', verbose_name='نویسندگان'),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='catalog.Category', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_of_publish',
            field=models.DateField(verbose_name='سال چاپ'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['bottom', 'right'], force_format=None, keep_meta=True, null=True, quality=100, size=[225, 225], upload_to='books_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('p', 'نسخه چاپی'), ('a', 'نسخه صوتی')], default='p', max_length=1, verbose_name='نوع چاپ'),
        ),
    ]
