# Generated by Django 3.1.7 on 2021-06-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_book_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('date_of_publish', 'title'), 'verbose_name': 'کتاب', 'verbose_name_plural': 'کتاب ها'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category',), 'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
